---

language: ruby

services:
  - docker

sudo: required

bundler_args: --without development

env:
  - INSTANCE=default-centos-7
  - INSTANCE=default-amazonlinux-201609

script:
  - bundle exec kitchen test $INSTANCE

after_script:
  - cat .kitchen/logs/kitchen.log

notifications:
  slack:
    secure: oSACXLjjocQ0sDE9VCUo2z1Tf7tRrevWwK4In1M7Q9uHlEEhmNO/MfFjJqtEHquxKE2qo+Q+PCCp3oYInxpe5hcu5Z1r81auVyThAnm898211iuNqFMi7yEsGa/ldtjQjJX1CJOCJ88Oo8N0JLebR80d9iTBcAb8C9iNSxiVtppZc2YnRJzT9NBjwjlNlsyDM04D2B9eu+Zvu5V4LtIVLnzSIiMj1CfC4CbUn4TXHqSiUDJDZf9iY80jaOXZgX3pChsiWAyijCUUPZnbukOglYjj0MRfgGLHLo0BsQvzgIWiJ6+Raa7mWEeJioJ2DcWxE+ezsixms+5GyG4Ng1PkhFDF0d1ZZO5b4y2xlBQ6O1fkUNr9DUvFyXMkaFjv1xUA7/L0Q8tfkG1IWgQ9FLlci7Ef0Pbbv3/h6LfZaHK1me1qhV8j9LxuLfxSVfuqiDmm6AFw5ajzwJ17QjCBvhtRYbEu68ocRbYk5UvCuZeqRLl3ikA5bJJ38sSqYty7nlZgxf8UHQEUTCkz+9SrcoVX8wIqgemwoH2Bidu3ux0+scD6tt9+BRohGsDQyEWfe9WZHPegaxQSaYYiQB0Aie9Xj5Fo5PkUurYmBcv7TxhDHvsKL6GrHdq9CnXAKnu+MpwrYkbroLaxfizZPpJ6nGpZu/f4sxKngKJoVBxwXt/lLY8=
